In [16]:
import torch
from torch import nn
from tqdm import trange

x = torch.tensor([[0, 0], [0, 1], [1, 0], [1, 1],]).float()
y = torch.tensor([0, 1, 1, 0]).float()

f1 = nn.Linear(2, 2)
act = nn.Sigmoid()
f2 = nn.Linear(2, 1)
params = list(f1.parameters()) + list(f2.parameters())
optim = torch.optim.Adam(params)

for _ in trange(10000):
    y_hat = f2(act(f1(x))).squeeze()
    error = y - y_hat
    loss = error.t().dot(error)
    optim.zero_grad()
    loss.backward()
    optim.step()

print()
print(y_hat)
print(f1.weight)
print(f1.bias)
print(loss.item())


100%|██████████| 10000/10000 [00:05<00:00, 1981.26it/s]


tensor([2.3842e-06, 1.0000e+00, 1.0000e+00, 3.3379e-06],
       grad_fn=<SqueezeBackward0>)
Parameter containing:
tensor([[ 5.2901,  5.5986],
        [-2.5225, -2.5720]], requires_grad=True)
Parameter containing:
tensor([-2.2109,  3.4602], requires_grad=True)
2.603428583825007e-11
