In [22]:
import torch
from torch import nn
from tqdm import trange

x = torch.tensor([[0, 0], [0, 1], [1, 0], [1, 1],]).float()
y = torch.tensor([0, 1, 1, 0]).float()

f1 = nn.Linear(2, 2)
act = nn.Sigmoid()
f2 = nn.Linear(2, 1)
params = list(f1.parameters()) + list(f2.parameters())
optim = torch.optim.Adam(params)

for _ in trange(10000):
    y_hat = f2(act(f1(x))).squeeze()
    error = y - y_hat
    loss = error.t().dot(error)
    optim.zero_grad()
    loss.backward()
    optim.step()

print()
print(y_hat)
print(f1.weight)
print(f1.bias)
print(loss.item())


100%|██████████| 10000/10000 [00:05<00:00, 1917.74it/s]


tensor([0.0034, 0.7075, 0.7539, 0.5305], grad_fn=<SqueezeBackward0>)
Parameter containing:
tensor([[6.8375, 6.9722],
        [1.3813, 1.5967]], requires_grad=True)
Parameter containing:
tensor([-0.1973, -0.2174], requires_grad=True)
0.4275449514389038
