In [15]:
import torch
from torch import nn
from tqdm import trange

x = torch.tensor([[0, 0], [0, 1], [1, 0], [1, 1],]).float()
y = torch.tensor([0, 1, 1, 0]).float()

f1 = nn.Linear(2, 2)
act = nn.Sigmoid()
f2 = nn.Linear(2, 1)
params = list(f1.parameters()) + list(f2.parameters())
optim = torch.optim.Adam(params)

for _ in trange(10000):
    y_hat = f2(act(f1(x))).squeeze()
    error = y - y_hat
    loss = error.t().dot(error)
    optim.zero_grad()
    loss.backward()
    optim.step()

print()
print(y_hat)
print(f1.weight)
print(f1.bias)
print(loss.item())


100%|██████████| 10000/10000 [00:05<00:00, 1944.60it/s]


tensor([4.7684e-07, 1.0000e+00, 1.0000e+00, 2.0266e-06],
       grad_fn=<SqueezeBackward0>)
Parameter containing:
tensor([[ 2.3230,  2.3103],
        [-4.2322, -4.1586]], requires_grad=True)
Parameter containing:
tensor([-3.2975,  0.8016], requires_grad=True)
9.723777338876971e-12
